Add ability generating manpage and documentation for BSD systems
skvadrik/re2c pull request #326
Opened 2020-10-19 20:03 UTC by sergeyklay

**Add ability generating manpage and documentation for BSD systems**

- Stripping headers may not work as expected, as man output differs on different systems. This should work now.
- Simplified output parsing procedure by replacing the regular expression by `TERM=dumb`.
- Stripping escape sequences.
- Added documentation about the intentions of this script.

**Check for `man` and `sed` on Windows when `RE2C_REBUILD_DOCS` is `ON`**

Windows does not have a native `man` and `sed` commands. Therefore, we are looking for the Cygwin versions of  `man` and `sed`.

**Rephrase error messages for `RE2C_REBUILD_DOCS=ON`**

This aims to provide a bit more clear error messages on regenerate manpage stage as well as documentation.

**Remove rst2man output redirection as it doesn't work on Windows**

There is no need for redirect output with `>` (which doesn't work on Windows) as this is how rst2man works:
```
  rst2man [options] [<source> [<destination>]]
```

---

For the discussion see: https://github.com/skvadrik/re2c/issues/325

2020-10-19 22:04 UTC, skvadrik requested changes
Great patch, made me learn about `col` and `grep -A`! They both seem to be non-POSIX (grep has no `-A`: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/grep.html, and col seems to have been excluded: https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap04.html). But I tested this both on Linux and FreeBSD and it works, so let's use them.

2020-10-19 22:15 UTC, skvadrik reviewed
Commit title is missing "for" (`Add the ability for generating...` or `Add the ability to generate...`).

2020-10-19 23:26 UTC, sergeyklay commented on build/gen_help.sh
> +    # 1. 'col -b' removes backspaces, 'col -x' replaces tabs with spaces
Yes, backspaces  produces the following output 
![image](https://user-images.githubusercontent.com/1256298/96521990-2a024000-127b-11eb-9cfc-84f91f5e1332.png)

and we unable to grep it.

Take a look, it is **NAME**:

![image](https://user-images.githubusercontent.com/1256298/96522021-3c7c7980-127b-11eb-8fa7-02cb519129fe.png)

I think **`[BS]`** here means go back for the one position and draw the letter on top of the same just to simulate bold face.

2020-10-19 23:33 UTC, sergeyklay commented on build/gen_help.sh
> +    # 1. 'col -b' removes backspaces, 'col -x' replaces tabs with spaces
Regarding tabs: I think there is a potential issue here. The width of tabs can vary, which can lead to different text widths in different terminals. Thus I chose a more predictable way to show the help text.

2020-10-19 23:52 UTC, sergeyklay commented on build/gen_help.sh
> +        | grep -A 100 USAGE         \
Good catch. Thank you!

2020-10-19 23:52 UTC, sergeyklay commented on build/gen_help.sh
> +    export MANWIDTH=100
Done

2020-10-20 06:09 UTC, skvadrik approved these changes

2020-10-20 06:09 UTC, skvadrik commented on build/gen_help.sh
> +    # 1. 'col -b' removes backspaces, 'col -x' replaces tabs with spaces
I see! What a weird behaviour. I wonder why it inserts backspaces on (almost) every character.

2020-10-20 06:34 UTC, merged